"""The NURBS HTTP service, tested end-to-end over the real ASGI app (no mocks) via ``httpx``
``ASGITransport`` on ``asyncio.run`` so background jobs actually progress. Mirrors the
capture/reconstruct/nerf API tests. Gated on ``fastapi``, so it self-skips where the web env is
not installed.

Two layers of coverage:

* **U8.2a — the HTTP shell** (auth / CORS / caps / validation / 404 / 409 / 429 / delete /
  health), driven with an injected ``fit_fn`` (the SPEC-12 §6.1 seam): ``create_app(fit_fn)`` has
  **no import-time dependency** on ``app.pipeline`` — these tests never touch it. A lightweight
  contract-shaped ``fit_fn`` keeps them deterministic and OCCT-free (a ``threading.Event`` gate
  holds a job in flight for the 409 / 429 paths); ``test_submit_poll_result_real_step_end_to_end``
  additionally drives the REAL ``occ_step.surfaces_json_to_step`` through OCCT via an injected fit.
* **U8.2b — the real mesh→fit E2E** (``test_real_*_end_to_end``), driving the PRODUCTION
  dispatcher ``app.main._load_pipeline_fit`` (NOT an injected double): a real base64 GLB fixture
  is submitted, polled to completion, and its ``{ step, surfaces, report }`` fetched — with real
  MLX fitting + real OCCT through the live ASGI service. ``dome.glb`` → an open single-patch STEP
  (``is_solid`` False), ``blob.glb`` → THE GATE: a watertight 6-patch all-NURBS solid that
  re-imports as one closed solid, and a genus-1 ``torus.glb`` fails cleanly (job ``failed`` → 500)
  without killing the service. Gated per-test on ``mlx.core``/``trimesh``/``OCC.Core.Geom``.
"""

import asyncio
import base64
import threading
from pathlib import Path

import pytest

pytest.importorskip("fastapi")
import httpx  # noqa: E402
from httpx import ASGITransport  # noqa: E402

from app.main import _load_pipeline_fit, create_app  # noqa: E402

# Real topology fixtures (committed, generated by tests/fixtures/generate_fixtures.py): dome.glb =
# open disk, blob.glb = closed genus-0, torus.glb = genus-1 (unsupported). Used by the U8.2b E2E.
FIXTURES = Path(__file__).resolve().parent / "fixtures"

# The FR-9 report fields the result must carry (SPEC-12 FR-9 / §6.1).
FR9_REPORT_KEYS = {
    "patches",
    "fitted_patches",
    "faceted_patches",
    "control_points",
    "degree_u",
    "degree_v",
    "iters",
    "chamfer",
    "scd",
    "rms_deviation",
    "max_deviation",
    "fidelity_tol",
    "is_solid",
    "is_valid",
    "mode",
}


def _client(app) -> httpx.AsyncClient:
    return httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://t")


def _body(**overrides) -> dict:
    """A minimal valid /fit body. ``glb_base64`` is any non-empty string — the shell does not decode
    it (GLB parsing is the injected pipeline's job); here ``fit_fn`` ignores it entirely."""
    return {"glb_base64": "Zm9v", **overrides}  # "foo"


def _glb_body(name: str, **overrides) -> dict:
    """A /fit body carrying a REAL base64-encoded fixture GLB (``dome.glb``/``blob.glb``/
    ``torus.glb``) — for the U8.2b E2E, where the production dispatcher actually decodes and fits it."""
    glb_b64 = base64.b64encode((FIXTURES / name).read_bytes()).decode("ascii")
    return {"glb_base64": glb_b64, **overrides}


def _contract_result(payload: dict) -> dict:
    """A contract-shaped (all-15-FR-9-keys) result that echoes the request params — no OCCT. Lets the
    transport tests assert the body flowed through ``fit_fn`` (``iters``/``mode``) without pythonocc."""
    report = {k: 0 for k in FR9_REPORT_KEYS}
    report.update(iters=payload["iters"], mode=payload["mode"], fidelity_tol=payload["fidelity_tol"])
    return {
        "step": "ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\nENDSEC;\nEND-ISO-10303-21;\n",
        "surfaces": {"surfaces": []},
        "report": report,
    }


def _make_gated_fit_fn(release: threading.Event):
    """A ``fit_fn`` that blocks (in the ``to_thread`` worker) until ``release`` is set, so a job can be
    held provably in flight for the 409 (result-before-done) and 429 (concurrency-cap) paths."""

    def fit_fn(payload: dict) -> dict:
        if not release.wait(timeout=10.0):
            raise TimeoutError("gated fit_fn was never released")
        return _contract_result(payload)

    return fit_fn


async def _drain(c: httpx.AsyncClient, job_id: str, tries: int = 400, delay: float = 0.02) -> str:
    """Poll status until the job is terminal (keeps worker threads from lingering after a test)."""
    state = "queued"
    for _ in range(tries):
        state = (await c.get(f"/jobs/{job_id}/status")).json()["state"]
        if state in ("completed", "failed"):
            break
        await asyncio.sleep(delay)
    return state


def test_health():
    app = create_app(_contract_result)

    async def run():
        async with _client(app) as c:
            r = await c.get("/health")
            assert r.status_code == 200
            assert r.json() == {"status": "ok", "service": "plastiq-nurbs"}

    asyncio.run(run())


def test_cors_header_present():
    app = create_app(_contract_result)

    async def run():
        async with _client(app) as c:
            r = await c.get("/health", headers={"Origin": "http://example.com"})
            assert r.status_code == 200
            assert "access-control-allow-origin" in r.headers

    asyncio.run(run())


def test_fit_validation_422_on_out_of_bounds_params():
    # §6.1 bounds are pydantic Field(...) bounds → 422 before any fit work.
    app = create_app(_contract_result)

    async def run():
        async with _client(app) as c:
            for bad in (
                {"degree": 1},  # < 2
                {"degree": 9},  # > 8
                {"grid": 3},  # < 4
                {"grid": 65},  # > 64
                {"iters": -1},  # < 0
                {"iters": 2001},  # > 2000
                {"mode": "spline"},  # not in the Literal
                {"fidelity_tol": 0.0},  # must be > 0
            ):
                r = await c.post("/fit", json=_body(**bad))
                assert r.status_code == 422, f"{bad} → {r.status_code}: {r.text}"
            # glb_base64 is required.
            assert (await c.post("/fit", json={})).status_code == 422

    asyncio.run(run())


def test_status_result_delete_unknown_id_404():
    app = create_app(_contract_result)

    async def run():
        async with _client(app) as c:
            assert (await c.get("/jobs/nope/status")).status_code == 404
            assert (await c.get("/jobs/nope/result")).status_code == 404
            assert (await c.delete("/jobs/nope")).status_code == 404

    asyncio.run(run())


def test_result_before_done_returns_409():
    release = threading.Event()
    app = create_app(_make_gated_fit_fn(release))

    async def run():
        async with _client(app) as c:
            try:
                job_id = (await c.post("/fit", json=_body())).json()["id"]
                # The job is gated open — it cannot complete until we set the event, so /result is 409.
                r = await c.get(f"/jobs/{job_id}/result")
                assert r.status_code == 409, r.text
            finally:
                release.set()
                await _drain(c, job_id)

    asyncio.run(run())


def test_failed_job_status_error_and_result_500():
    # A fit_fn that raises → job `failed`: status carries the error, /result is 500 (§6.1).
    def boom(payload: dict) -> dict:
        raise ValueError("fit exploded")

    app = create_app(boom)

    async def run():
        async with _client(app) as c:
            job_id = (await c.post("/fit", json=_body())).json()["id"]
            assert await _drain(c, job_id) == "failed"
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert status["error"] and "fit exploded" in status["error"]
            r = await c.get(f"/jobs/{job_id}/result")
            assert r.status_code == 500, r.text
            assert "fit exploded" in r.json()["detail"]

    asyncio.run(run())


def test_delete_returns_204_then_404():
    app = create_app(_contract_result)

    async def run():
        async with _client(app) as c:
            job_id = (await c.post("/fit", json=_body())).json()["id"]
            assert (await c.delete(f"/jobs/{job_id}")).status_code == 204
            # The record is gone: subsequent status/result/delete are all 404.
            assert (await c.get(f"/jobs/{job_id}/status")).status_code == 404
            assert (await c.delete(f"/jobs/{job_id}")).status_code == 404

    asyncio.run(run())


def test_concurrency_cap_returns_429(monkeypatch):
    # NURBS_MAX_CONCURRENT_JOBS is read inside create_app, so setenv-then-create configures the cap.
    monkeypatch.setenv("NURBS_MAX_CONCURRENT_JOBS", "1")
    release = threading.Event()
    app = create_app(_make_gated_fit_fn(release))

    async def run():
        async with _client(app) as c:
            job_id = None
            try:
                r1 = await c.post("/fit", json=_body())
                assert r1.status_code == 200, r1.text
                job_id = r1.json()["id"]
                # The first job is gated in flight (non-terminal), so it holds the cap of 1.
                r2 = await c.post("/fit", json=_body())
                assert r2.status_code == 429, r2.text
            finally:
                release.set()
                if job_id is not None:
                    await _drain(c, job_id)

    asyncio.run(run())


def test_max_concurrent_zero_or_negative_clamps_to_one(monkeypatch):
    # A 0/negative NURBS_MAX_CONCURRENT_JOBS must NOT wedge the service (every /fit → 429 silently).
    # It resolves to a floor of 1, so at least one job is always accepted.
    for bad_cap in ("0", "-3"):
        monkeypatch.setenv("NURBS_MAX_CONCURRENT_JOBS", bad_cap)
        app = create_app(_contract_result)

        async def run():
            async with _client(app) as c:
                r = await c.post("/fit", json=_body())
                assert r.status_code == 200, f"cap={bad_cap!r} → {r.status_code}: {r.text}"
                await _drain(c, r.json()["id"])

        asyncio.run(run())


def test_non_integer_max_concurrent_raises_clear_config_error(monkeypatch):
    # A non-integer NURBS_MAX_CONCURRENT_JOBS must fail LOUDLY at create_app with a clear error
    # naming the env var — not an opaque `int()` ValueError at module import.
    monkeypatch.setenv("NURBS_MAX_CONCURRENT_JOBS", "not-a-number")
    with pytest.raises(RuntimeError, match="NURBS_MAX_CONCURRENT_JOBS"):
        create_app(_contract_result)


def test_auth_bearer_guards_fit_and_delete(monkeypatch):
    # NURBS_API_KEY set ⇒ POST /fit and DELETE require the bearer; 401 without, 200/204 with.
    monkeypatch.setenv("NURBS_API_KEY", "s3cret")
    app = create_app(_contract_result)
    auth = {"Authorization": "Bearer s3cret"}

    async def run():
        async with _client(app) as c:
            assert (await c.post("/fit", json=_body())).status_code == 401  # no header
            assert (
                await c.post("/fit", json=_body(), headers={"Authorization": "Bearer wrong"})
            ).status_code == 401  # wrong key
            r = await c.post("/fit", json=_body(), headers=auth)
            assert r.status_code == 200, r.text  # correct key
            job_id = r.json()["id"]
            # /health and reads stay open; only the mutating endpoints are guarded.
            assert (await c.get("/health")).status_code == 200
            assert (await c.get(f"/jobs/{job_id}/status")).status_code == 200
            assert (await c.delete(f"/jobs/{job_id}")).status_code == 401  # DELETE guarded too
            assert (await c.delete(f"/jobs/{job_id}", headers=auth)).status_code == 204

    asyncio.run(run())


def test_auth_open_when_key_unset(monkeypatch):
    monkeypatch.delenv("NURBS_API_KEY", raising=False)
    app = create_app(_contract_result)

    async def run():
        async with _client(app) as c:
            assert (await c.post("/fit", json=_body())).status_code == 200  # open dev default

    asyncio.run(run())


def test_submit_poll_result_real_step_end_to_end():
    """The headline test: submit → poll → fetch a REAL OCCT-produced STEP through the injected fit_fn
    (not a stub). Gated on pythonocc."""
    pytest.importorskip("OCC.Core.Geom")
    from app.occ_step import surfaces_json_to_step

    def real_fit_fn(payload: dict) -> dict:
        # A valid §6.2 bicubic patch (5×5 poles, one interior knot ⇒ a genuine multi-span B-spline,
        # not a Bézier-degenerate single span) driven through the REAL JSON→OCCT→STEP conversion.
        n = 5
        poles = [
            [
                [
                    i / (n - 1),
                    j / (n - 1),
                    0.2 * (1 - (2 * i / (n - 1) - 1) ** 2) * (1 - (2 * j / (n - 1) - 1) ** 2),
                ]
                for j in range(n)
            ]
            for i in range(n)
        ]
        surfaces = {
            "surfaces": [
                {
                    "poles": poles,
                    "weights": [],
                    "u_knots": [0.0, 0.5, 1.0],
                    "v_knots": [0.0, 0.5, 1.0],
                    "u_mults": [4, 1, 4],
                    "v_mults": [4, 1, 4],
                    "u_degree": 3,
                    "v_degree": 3,
                    "u_periodic": False,
                    "v_periodic": False,
                }
            ]
        }
        step, faces = surfaces_json_to_step(surfaces)
        report = {
            "patches": faces,
            "fitted_patches": faces,
            "faceted_patches": 0,
            "control_points": n * n,
            "degree_u": 3,
            "degree_v": 3,
            "iters": payload["iters"],
            "chamfer": 0.0,
            "scd": 0.0,
            "rms_deviation": 0.0,
            "max_deviation": 0.0,
            "fidelity_tol": payload["fidelity_tol"],
            "is_solid": False,
            "is_valid": True,
            "mode": payload["mode"],
        }
        return {"step": step, "surfaces": surfaces, "report": report}

    app = create_app(real_fit_fn)

    async def run():
        async with _client(app) as c:
            r = await c.post("/fit", json=_body(iters=200, mode="auto"))
            assert r.status_code == 200, r.text
            assert r.json()["state"] in ("queued", "running")
            job_id = r.json()["id"]

            state = await _drain(c, job_id, tries=1500, delay=0.05)
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert state == "completed", f"job ended in {state}: {status}"

            result = await c.get(f"/jobs/{job_id}/result")
            assert result.status_code == 200, result.text
            body = result.json()
            # Real STEP text from OCCT.
            assert "B_SPLINE_SURFACE_WITH_KNOTS" in body["step"]
            # `surfaces` is the nested Surfaces object {"surfaces": [...]}, not a bare list (§6.2).
            assert body["surfaces"]["surfaces"], "result.surfaces must be the nested Surfaces object"
            # The full FR-9 report shape.
            assert set(body["report"].keys()) == FR9_REPORT_KEYS
            # The request body flowed through fit_fn.
            assert body["report"]["iters"] == 200
            assert body["report"]["mode"] == "auto"
            assert body["report"]["control_points"] == 25

    asyncio.run(run())


# --- U8.2b: the REAL mesh→fit E2E (production dispatcher, no injected double, real OCCT) --------
#
# These drive create_app(_load_pipeline_fit) — the SAME dispatcher `uvicorn app.main:app` serves —
# so a real base64 GLB flows: HTTP body → decode → meshio.detect_mode → open/closed pipeline →
# real MLX fit + real OCCT STEP → {step, surfaces, report}, all through the live ASGI service.
# Gated per-test on the fitting deps (the module gate is only fastapi, for the shell tests above).


def test_real_dome_open_end_to_end():
    """dome.glb (OPEN) through the LIVE service: submit → poll → a real single-patch STEP.

    ``iters=0`` is pinned for a DETERMINISTIC result — open-mode ``iters>0`` refine has a known
    thin-margin improvement property being investigated separately, so the E2E stays at pure LSQ
    (``grid=8`` matches the proven open pipeline; dome's 7-vertex boundary arcs interpolate there).
    """
    pytest.importorskip("mlx.core")
    pytest.importorskip("trimesh")
    pytest.importorskip("OCC.Core.Geom")

    app = create_app(_load_pipeline_fit)  # the production dispatcher, not an injected double

    async def run():
        async with _client(app) as c:
            r = await c.post("/fit", json=_glb_body("dome.glb", mode="auto", grid=8, iters=0))
            assert r.status_code == 200, r.text
            assert r.json()["state"] in ("queued", "running")
            job_id = r.json()["id"]

            state = await _drain(c, job_id, tries=2000, delay=0.05)
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert state == "completed", f"dome job ended in {state}: {status}"

            result = await c.get(f"/jobs/{job_id}/result")
            assert result.status_code == 200, result.text
            body = result.json()
            # Real OCCT STEP: exactly one B-spline face (the single open patch).
            assert body["step"].count("B_SPLINE_SURFACE_WITH_KNOTS") == 1, body["step"]
            # A single-patch nested Surfaces payload (§6.2).
            assert len(body["surfaces"]["surfaces"]) == 1
            report = body["report"]
            assert set(report.keys()) == FR9_REPORT_KEYS  # open mode carries the 15-key set
            assert report["mode"] == "open"
            assert report["is_solid"] is False  # a single open patch is a face, not a solid
            assert report["is_valid"] is True
            assert report["iters"] == 0

    asyncio.run(run())


def test_real_blob_closed_end_to_end(tmp_path):
    """THE GATE through the LIVE service: blob.glb (CLOSED) → a watertight 6-patch all-NURBS solid
    STEP that re-imports as one closed solid of six B-spline faces with zero free edges.

    ``grid=8`` is pinned in the request — NOT the §6.1 HTTP default of 16: grid=8 matches the proven
    gate in tests/test_pipeline_closed.py. The served default grid=16 also closes (SPEC-12 §8 U7)
    and is pinned separately by ``test_real_blob_closed_default_grid_end_to_end``. ``iters=0`` (closed
    mode records but does not apply iters). No mocks — the production dispatcher runs the real closed
    pipeline + real OCCT sew/solid checks.
    """
    pytest.importorskip("mlx.core")
    pytest.importorskip("trimesh")
    pytest.importorskip("OCC.Core.Geom")

    app = create_app(_load_pipeline_fit)

    async def run() -> str:
        async with _client(app) as c:
            r = await c.post("/fit", json=_glb_body("blob.glb", mode="auto", grid=8, iters=0))
            assert r.status_code == 200, r.text
            job_id = r.json()["id"]

            state = await _drain(c, job_id, tries=2000, delay=0.05)
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert state == "completed", f"blob job ended in {state}: {status}"

            result = await c.get(f"/jobs/{job_id}/result")
            assert result.status_code == 200, result.text
            body = result.json()

            step = body["step"]
            # Six non-rational B-spline faces (the compact-knot, watertight handoff).
            assert step.count("B_SPLINE_SURFACE_WITH_KNOTS") == 6, step.count(
                "B_SPLINE_SURFACE_WITH_KNOTS"
            )
            assert "RATIONAL_B_SPLINE_SURFACE" not in step
            assert len(body["surfaces"]["surfaces"]) == 6

            report = body["report"]
            # Closed mode's report is a SUPERSET of the open 15-key set (+free_edges, +volume).
            assert FR9_REPORT_KEYS <= set(report.keys())
            assert {"free_edges", "volume"} <= set(report.keys())
            assert report["mode"] == "closed"
            # Closure verified, never assumed — straight from OCCT (SPEC-12 FR-4).
            assert report["is_solid"] is True, "blob did not close into a watertight solid"
            assert report["is_valid"] is True
            assert report["free_edges"] == 0
            assert report["fitted_patches"] == 6
            assert report["faceted_patches"] == 0
            return step

    step = asyncio.run(run())

    # Re-import the LIVE-service STEP as a real B-rep: exactly one closed solid of six NURBS faces.
    from OCC.Core.IFSelect import IFSelect_RetDone
    from OCC.Core.STEPControl import STEPControl_Reader
    from OCC.Core.TopAbs import TopAbs_FACE, TopAbs_SOLID
    from OCC.Core.TopExp import TopExp_Explorer

    def _count(shape, kind) -> int:
        explorer = TopExp_Explorer(shape, kind)
        n = 0
        while explorer.More():
            n += 1
            explorer.Next()
        return n

    path = tmp_path / "reimport.step"
    path.write_text(step, encoding="utf-8")
    reader = STEPControl_Reader()
    assert reader.ReadFile(str(path)) == IFSelect_RetDone
    assert reader.TransferRoots() > 0
    shape = reader.OneShape()
    assert _count(shape, TopAbs_SOLID) == 1, "STEP is not a single closed solid"
    assert _count(shape, TopAbs_FACE) == 6, "solid does not have exactly 6 NURBS faces"


def test_real_torus_unsupported_fails_clean_500():
    """An unsupported mesh (genus-1 torus.glb) fails the job CLEANLY: /result 500 with the topology
    error surfaced — and the service stays alive (/health still 200), not a dead service (FR-9)."""
    pytest.importorskip("mlx.core")
    pytest.importorskip("trimesh")
    pytest.importorskip("OCC.Core.Geom")

    app = create_app(_load_pipeline_fit)

    async def run():
        async with _client(app) as c:
            r = await c.post("/fit", json=_glb_body("torus.glb", mode="auto"))
            assert r.status_code == 200, r.text  # accepted; the failure surfaces on poll
            job_id = r.json()["id"]

            state = await _drain(c, job_id, tries=800, delay=0.02)
            assert state == "failed", f"genus-1 torus should fail, ended in {state}"
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert status["error"], "a failed job must carry an error message"
            assert "genus" in status["error"] or "supported" in status["error"].lower()

            res = await c.get(f"/jobs/{job_id}/result")
            assert res.status_code == 500, res.text
            # The service survived the failed fit — a bad mesh is a failed job, not a dead service.
            assert (await c.get("/health")).status_code == 200

    asyncio.run(run())


def test_real_dome_mode_mismatch_fails_clean_500():
    """A VALID mesh with the WRONG explicit mode fails cleanly through the LIVE service: dome.glb
    (open) forced ``mode="closed"`` hits ``detect_mode``'s ``topology.mode != requested`` branch
    (distinct from the torus genus-raise and the ``mode="spline"`` 422) → job ``failed`` → /result
    500 surfacing the mismatch — and /health stays 200. ``iters=0`` (the mismatch raises before any
    fit, so no refine runs regardless)."""
    pytest.importorskip("mlx.core")
    pytest.importorskip("trimesh")
    pytest.importorskip("OCC.Core.Geom")

    app = create_app(_load_pipeline_fit)

    async def run():
        async with _client(app) as c:
            # mode="closed" is a valid §6.1 Literal (so NOT a 422) but wrong for the open dome, so it
            # reaches the dispatcher and detect_mode rejects it — unlike {"mode": "spline"} (422).
            r = await c.post("/fit", json=_glb_body("dome.glb", mode="closed", iters=0))
            assert r.status_code == 200, r.text  # accepted; the mismatch surfaces on poll
            job_id = r.json()["id"]

            state = await _drain(c, job_id, tries=800, delay=0.02)
            assert state == "failed", f"open dome forced closed should fail, ended in {state}"
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert status["error"], "a failed job must carry an error message"

            res = await c.get(f"/jobs/{job_id}/result")
            assert res.status_code == 500, res.text
            detail = res.json()["detail"]
            # The detect_mode mismatch is surfaced (not some other 500): it names the requested mode
            # AND the real detected topology, proving detect_mode ran and hit the mismatch branch.
            assert 'requested mode "closed"' in detail, detail
            assert "the mesh is open" in detail, detail
            # A bad explicit mode is a failed job, not a dead service.
            assert (await c.get("/health")).status_code == 200

    asyncio.run(run())


def test_real_blob_closed_default_grid_end_to_end():
    """The served §6.1 DEFAULT closes: blob.glb (closed) with NO ``grid`` override — so FitBody's
    default grid=16 binds — → a watertight 6-patch NURBS solid through the LIVE service.

    The other closed E2E pins grid=8 (the proven pipeline gate); this pins the served default so a
    regression in FitBody's ``grid`` default (16 → anything) is caught. grid=16 closure is sound per
    SPEC-12 §8 U7 (holds at grid 8/12/16). ``iters=0`` (closed mode records but does not apply iters);
    no mocks — the production dispatcher runs the real closed pipeline + real OCCT sew/solid checks."""
    pytest.importorskip("mlx.core")
    pytest.importorskip("trimesh")
    pytest.importorskip("OCC.Core.Geom")

    app = create_app(_load_pipeline_fit)

    async def run():
        async with _client(app) as c:
            # No grid override → the request binds FitBody's default grid=16 (the served §6.1 default).
            r = await c.post("/fit", json=_glb_body("blob.glb", mode="auto", iters=0))
            assert r.status_code == 200, r.text
            job_id = r.json()["id"]

            state = await _drain(c, job_id, tries=2000, delay=0.05)
            status = (await c.get(f"/jobs/{job_id}/status")).json()
            assert state == "completed", f"blob job (default grid) ended in {state}: {status}"

            result = await c.get(f"/jobs/{job_id}/result")
            assert result.status_code == 200, result.text
            report = result.json()["report"]
            # The default grid=16 still closes into a watertight solid (SPEC-12 §8 U7), verified from
            # OCCT — never assumed.
            assert report["mode"] == "closed"
            assert report["is_solid"] is True, "default grid=16 did not close into a watertight solid"
            assert report["free_edges"] == 0
            assert report["fitted_patches"] == 6
            # Pin the grid actually used: 6 patches × a 16×16 control net (control_points scales with
            # grid). This is what makes the served default GRID=16 regression-caught — is_solid /
            # free_edges / fitted_patches alone also hold at the grid=8 sibling, so a 16→8 (or 16→12)
            # default regression would pass those but change control_points here and fail.
            assert report["control_points"] == 6 * 16 * 16  # 1536

    asyncio.run(run())
